const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const provinces=['کندهار','کابل','هرات','بلخ','ننګرهار','هلمند','غزني','فراه','نیمروز','زابل','ارزګان','پکتیا','پکتیکا','خوست','کندز','تخار','بدخشان','بغلان','سمنګان','سرپل','جوزجان','فاریاب','بادغیس','غور','دایکندي','بامیان','پروان','کاپیسا','پنجشېر','لغمان','کونړ','نورستان','لوګر','میدان وردګ'];
const roleNames={admin:'اډمین',agent:'شاګرد',dispatcher:'د لېږلو مسؤل'};
const statusNames={registered:'ثبت شوی',sent:'ولېږل شو',delivered:'تسلیم شو'};
let profile=null,currentOrders=[],editingPhoto=null,ordersOffset=0,hasMoreOrders=false;
const ORDER_PAGE_SIZE=20;

function show(id){$$('.view').forEach(v=>v.classList.toggle('active',v.id===id));$$('.nav').forEach(n=>n.classList.toggle('active',n.dataset.view===id))}
function toast(msg){$('#toast').textContent=msg;$('#toast').classList.add('show');setTimeout(()=>$('#toast').classList.remove('show'),2800)}
function busy(form,on){const b=form.querySelector('button[type=submit]');if(b)b.disabled=on}
function digits(v){return String(v??'').replace(/[۰-۹]/g,c=>'۰۱۲۳۴۵۶۷۸۹'.indexOf(c)).replace(/[٠-٩]/g,c=>'٠١٢٣٤٥٦٧٨٩'.indexOf(c)).replace(/\s+/g,'')}
function phone(v){let p=digits(v).replace(/\D/g,'');if(p.startsWith('0093'))p='0'+p.slice(4);else if(p.startsWith('93'))p='0'+p.slice(2);if(p.length===9&&!p.startsWith('0'))p='0'+p;return p}
function number(v){return Number(v||0).toLocaleString('en-US')}
function kabulParts(value){return Object.fromEntries(new Intl.DateTimeFormat('en-GB',{timeZone:'Asia/Kabul',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hour12:false}).formatToParts(new Date(value)).map(p=>[p.type,p.value]))}
function orderDateTime(v){const p=kabulParts(v);return `${p.year}/${p.month}/${p.day} — ${p.hour}:${p.minute}`}
function businessDayKey(value=new Date()){const shifted=new Date(new Date(value).getTime()+(270-360)*60000);return `${shifted.getUTCFullYear()}-${String(shifted.getUTCMonth()+1).padStart(2,'0')}-${String(shifted.getUTCDate()).padStart(2,'0')}`}
function businessDayLabel(key){const [y,m,d]=key.split('-');return `${y}/${m}/${d}`}
function escapeHtml(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
async function api(path,opts={}){const r=await fetch('/api'+path,{credentials:'same-origin',...opts,headers:{...(opts.body instanceof FormData?{}:{'Content-Type':'application/json'}),...(opts.headers||{})}});let data={};try{data=await r.json()}catch(_){}if(!r.ok)throw new Error(data.error||'له سرور سره ستونزه ده');return data}
function errorText(e){return e?.message||'ستونزه رامنځته شوه'}

function compressImage(file,maxSide=900,quality=.68){return new Promise(resolve=>{if(!file||!file.size)return resolve(file);if(file.size<180000&&/image\/jpe?g/i.test(file.type||''))return resolve(file);const img=new Image(),url=URL.createObjectURL(file);img.onload=()=>{try{let w=img.naturalWidth||img.width,h=img.naturalHeight||img.height,s=Math.min(1,maxSide/Math.max(w,h));w=Math.max(1,Math.round(w*s));h=Math.max(1,Math.round(h*s));const c=document.createElement('canvas');c.width=w;c.height=h;c.getContext('2d').drawImage(img,0,0,w,h);c.toBlob(b=>{URL.revokeObjectURL(url);resolve(b||file)},'image/jpeg',quality)}catch(_){URL.revokeObjectURL(url);resolve(file)}};img.onerror=()=>{URL.revokeObjectURL(url);resolve(file)};img.src=url})}

$$('.tab').forEach(b=>b.onclick=()=>{$$('.tab').forEach(x=>x.classList.toggle('active',x===b));$$('#authView .form').forEach(f=>f.classList.toggle('active',f.id===b.dataset.auth))});
$$('.nav').forEach(b=>b.onclick=()=>{show(b.dataset.view);if(b.dataset.view==='adminView')loadUsers();if(b.dataset.view==='reportView')loadReport()});
provinces.forEach(p=>$('#orderForm select').add(new Option(p,p)));

$('#registerForm').onsubmit=async e=>{e.preventDefault();const form=e.currentTarget,f=new FormData(form),p=phone(f.get('phone')),pin=digits(f.get('pin'));if(!/^07\d{8}$/.test(p))return toast('د موبایل شمېره سمه ولیکئ');if(!/^\d{4}$/.test(pin))return toast('څلور عددي PIN ولیکئ');busy(form,true);try{const photo=await compressImage(f.get('profilePhoto'),600,.7),fd=new FormData();fd.set('name',f.get('name').trim());fd.set('phone',p);fd.set('pin',pin);fd.set('photo',photo,'profile.jpg');await api('/register',{method:'POST',body:fd});form.reset();toast('ثبت شو؛ د اډمین تایید ته انتظار وکړئ');$$('.tab')[0].click()}catch(err){toast(errorText(err))}finally{busy(form,false)}};

$('#loginForm').onsubmit=async e=>{e.preventDefault();const form=e.currentTarget,p=phone(form.phone.value),pin=digits(form.pin.value);form.phone.value=p;form.pin.value=pin;if(!/^07\d{8}$/.test(p))return toast('د موبایل شمېره سمه ولیکئ');if(!/^\d{4}$/.test(pin))return toast('څلور عددي PIN ولیکئ');busy(form,true);try{await api('/login',{method:'POST',body:JSON.stringify({phone:p,pin})});await boot()}catch(err){toast(errorText(err))}finally{busy(form,false)}};
$('#logoutBtn').onclick=$('#pendingLogout').onclick=async()=>{try{await api('/logout',{method:'POST',body:'{}'})}catch(_){}profile=null;currentOrders=[];$('#bottomNav').classList.add('hidden');$('#logoutBtn').classList.add('hidden');show('authView')};

async function boot(){try{const d=await api('/me');profile=d.profile;route()}catch(_){show('authView')}}
function route(){if(!profile)return show('authView');$('#serviceNotice').classList.add('hidden');$('#logoutBtn').classList.remove('hidden');if(profile.status!=='approved'){show('pendingView');return}$('#bottomNav').classList.remove('hidden');$('#adminNav').classList.toggle('hidden',profile.role!=='admin');$('#newOrderBtn').classList.toggle('hidden',profile.role!=='agent');$('#userName').textContent=profile.full_name;$('#avatarFallback').textContent=profile.full_name?.[0]||'ا';$('#avatar').classList.toggle('has-photo',!!profile.selfie_path);if(profile.selfie_path)$('#avatarImg').src='/api/photo/'+encodeURIComponent(profile.selfie_path);$('#roleBadge').textContent=roleNames[profile.role];$('#ordersTitle').textContent=profile.role==='agent'?'زما وروستي آرډرونه':'ټول وروستي آرډرونه';show('homeView');loadOrders(true)}

async function loadOrders(reset=true){if(reset){ordersOffset=0;currentOrders=[]}try{const d=await api(`/orders?offset=${ordersOffset}&limit=${ORDER_PAGE_SIZE}`);hasMoreOrders=d.hasMore;currentOrders=reset?d.orders:currentOrders.concat(d.orders);ordersOffset=currentOrders.length;renderOrders();if(reset)loadStats()}catch(e){toast(errorText(e))}}
function renderOrders(){const box=$('#ordersList');box.innerHTML='';$('#ordersEmpty').style.display=currentOrders.length?'none':'block';box.innerHTML=currentOrders.map(o=>{const canEdit=profile.role==='agent'&&o.created_by===profile.id&&o.status==='registered',canMove=profile.role==='dispatcher'&&o.status==='registered',action=o.province==='کندهار'?'تسلیم شو':'ولېږل شو';return `<article class="order-card"><img src="/api/photo/${encodeURIComponent(o.photo_path)}" alt="${escapeHtml(o.product_name)}" loading="lazy"><div class="order-main"><div class="order-top"><h4>${escapeHtml(o.product_name)}</h4><span class="badge ${o.status}">${statusNames[o.status]}</span></div><div class="order-meta"><span>📍 ${escapeHtml(o.province)}</span><span>📦 ${number(o.quantity)}</span><span>☎ ${escapeHtml(o.customer_phone)}</span>${profile.role!=='agent'?`<span>👤 ${escapeHtml(o.creator_name||'نوم نه دی موندل شوی')}</span>`:''}</div><div class="order-meta"><span>📅 ثبت: ${orderDateTime(o.created_at)}</span></div><div class="order-meta"><span>📌 ادرس: ${escapeHtml(o.address)}</span></div><div class="order-foot"><strong>${number(o.price)} ؋</strong><div class="order-actions">${canEdit?`<button class="small-btn" data-edit="${o.id}">اصلاح</button>`:''}${canMove?`<button class="small-btn action" data-move="${o.id}">${action}</button>`:''}</div></div></div></article>`}).join('');$$('[data-edit]').forEach(b=>b.onclick=()=>openOrder(b.dataset.edit));$$('[data-move]').forEach(b=>b.onclick=()=>advance(b.dataset.move));$('#moreOrdersBtn').classList.toggle('hidden',!hasMoreOrders)}
$('#moreOrdersBtn').onclick=()=>loadOrders(false);
async function loadStats(){try{const d=await api('/stats');$('#otherProvinceCount').textContent=number(d.otherCount);$('#otherProvinceMoney').textContent=number(d.otherMoney);$('#kandaharCount').textContent=number(d.kandaharCount);$('#kandaharMoney').textContent=number(d.kandaharMoney)}catch(_){}}

$('#newOrderBtn').onclick=()=>openOrder();$('#closeOrder').onclick=()=>$('#orderDialog').close();
function openOrder(id){const f=$('#orderForm');f.reset();f.id.value='';editingPhoto=null;$('#photoPreview').style.display='none';$('.product-photo span').style.display='block';$('#orderKicker').textContent='نوی آرډر';$('#deleteOrderBtn').classList.add('hidden');if(id){const o=currentOrders.find(x=>String(x.id)===String(id));if(!o)return;f.id.value=o.id;['product_name','customer_phone','province','quantity','address','price'].forEach(k=>f.elements[k].value=o[k]);editingPhoto=o.photo_path;$('#orderKicker').textContent='آرډر اصلاح کړئ';if(profile.role==='agent'&&o.created_by===profile.id&&o.status==='registered'){$('#deleteOrderBtn').classList.remove('hidden');$('#deleteOrderBtn').dataset.id=o.id}$('#photoPreview').src='/api/photo/'+encodeURIComponent(o.photo_path);$('#photoPreview').style.display='block';$('.product-photo span').style.display='none'}$('#orderDialog').showModal()}
$('#orderForm [name=photo]').onchange=e=>{const file=e.target.files[0];if(!file)return;$('#photoPreview').src=URL.createObjectURL(file);$('#photoPreview').style.display='block';$('.product-photo span').style.display='none'};
$('#orderForm').onsubmit=async e=>{e.preventDefault();const form=e.currentTarget,f=new FormData(form),id=f.get('id'),file=f.get('photo');if(!id&&(!file||!file.size))return toast('د جنس عکس واخلئ');busy(form,true);try{const fd=new FormData();for(const k of ['id','product_name','customer_phone','province','quantity','address','price'])fd.set(k,f.get(k));if(file&&file.size)fd.set('photo',await compressImage(file,900,.68),'order.jpg');await api('/orders',{method:'POST',body:fd});$('#orderDialog').close();toast(id?'آرډر اصلاح شو':'آرډر ثبت شو');loadOrders(true)}catch(err){toast(errorText(err))}finally{busy(form,false)}};
$('#deleteOrderBtn').onclick=async()=>{const id=$('#deleteOrderBtn').dataset.id;if(!id||!confirm('ایا ډاډه یاست چې دا جنس مکمل ډیلیټ کړئ؟'))return;try{await api('/orders/'+id,{method:'DELETE',body:'{}'});$('#orderDialog').close();toast('جنس مکمل ډیلیټ شو');loadOrders(true)}catch(e){toast(errorText(e))}};
async function advance(id){try{const d=await api('/orders/'+id+'/advance',{method:'POST',body:'{}'});toast(statusNames[d.status]);loadOrders(true)}catch(e){toast(errorText(e))}}

async function loadUsers(){try{const d=await api('/users');const pending=d.users.filter(u=>u.status==='pending'),approved=d.users.filter(u=>u.status==='approved'&&u.role!=='admin');$('#pendingCount').textContent=number(pending.length);$('#usersEmpty').style.display=pending.length?'none':'block';$('#pendingUsers').innerHTML=pending.map(u=>userCard(u,true)).join('');$('#approvedUsers').innerHTML=approved.map(u=>userCard(u,false)).join('');$$('[data-user-action]').forEach(b=>b.onclick=()=>userAction(b.dataset.uid,b.dataset.userAction));$$('[data-reset-pin]').forEach(b=>b.onclick=()=>openResetPin(b.dataset.resetPin,b.dataset.name))}catch(e){toast(errorText(e))}}
function userCard(u,pending){return `<article class="user-card"><div class="user-top"><div class="user-identity">${u.selfie_path?`<img class="user-photo" src="/api/photo/${encodeURIComponent(u.selfie_path)}" alt="${escapeHtml(u.full_name)}">`:''}<div><h4>${escapeHtml(u.full_name)}</h4><p>☎ ${escapeHtml(u.phone)} • ${roleNames[u.role]}</p></div></div><span class="badge">${pending?'انتظار':'تایید'}</span></div><div class="user-actions">${pending?`<button class="approve" data-uid="${u.id}" data-user-action="agent">د شاګرد په توګه تایید</button><button class="dispatch" data-uid="${u.id}" data-user-action="dispatcher">د لېږونکي په توګه تایید</button><button class="reject" data-uid="${u.id}" data-user-action="reject">رد</button>`:`<button class="approve" data-uid="${u.id}" data-user-action="agent">شاګرد</button><button class="dispatch" data-uid="${u.id}" data-user-action="dispatcher">لېږونکی</button><button class="reset-pin" data-reset-pin="${u.id}" data-name="${escapeHtml(u.full_name)}">PIN بدلول</button><button class="reject" data-uid="${u.id}" data-user-action="reject">بندول</button>`}</div></article>`}
async function userAction(uid,action){try{await api('/users/'+uid,{method:'PATCH',body:JSON.stringify({action})});toast('حساب تازه شو');loadUsers()}catch(e){toast(errorText(e))}}
function openResetPin(uid,name){const f=$('#resetPinForm');f.reset();f.uid.value=uid;$('#resetPinUser').textContent=`د ${name} لپاره نوی PIN وټاکئ.`;$('#resetPinDialog').showModal()}
$('#closeResetPin').onclick=()=>$('#resetPinDialog').close();
$('#resetPinForm').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.currentTarget),pin=digits(f.get('pin'));if(!/^\d{4}$/.test(pin))return toast('څلور عددي PIN ولیکئ');busy(e.currentTarget,true);try{await api('/users/'+f.get('uid')+'/pin',{method:'PATCH',body:JSON.stringify({pin})});$('#resetPinDialog').close();toast('نوی PIN ثبت شو')}catch(err){toast(errorText(err))}finally{busy(e.currentTarget,false)}};

$('#refreshBtn').onclick=loadReport;
async function loadReport(){try{const d=await api('/report'),rows=d.days,today=rows.find(x=>x.key===businessDayKey())||{otherCount:0,otherMoney:0,kandaharCount:0,kandaharMoney:0};$('#reportSummary').innerHTML=`<article><strong>${number(today.otherCount)} جنس</strong><span>نن نورو ولایتونو ته</span><b>${number(today.otherMoney)} ؋</b></article><article><strong>${number(today.kandaharCount)} جنس</strong><span>نن کندهار کې</span><b>${number(today.kandaharMoney)} ؋</b></article><article><strong>${number(today.otherCount+today.kandaharCount)}</strong><span>نن ټول</span></article>`;$('#reportUsers').innerHTML=rows.map((x,i)=>`<article class="weekly-card"><div class="weekly-title"><div><small>${i===0&&x.key===businessDayKey()?'نن':'ورځ'}</small><h3>${businessDayLabel(x.key)}</h3></div><strong>${number(x.otherCount+x.kandaharCount)} جنس</strong></div><div class="weekly-grid"><span>نور ولایتونه<b>${number(x.otherCount)} • ${number(x.otherMoney)} ؋</b></span><span>کندهار<b>${number(x.kandaharCount)} • ${number(x.kandaharMoney)} ؋</b></span></div></article>`).join('')}catch(e){toast(errorText(e))}}

let deferredInstall=null;window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredInstall=e});
$('#installBtn').onclick=async()=>{if(deferredInstall){deferredInstall.prompt();await deferredInstall.userChoice;deferredInstall=null}else $('#installDialog').showModal()};
$('#closeInstall').onclick=$('#installOk').onclick=()=>$('#installDialog').close();
$('#forgotPinBtn').onclick=()=>$('#forgotPinDialog').showModal();$('#closeForgotPin').onclick=$('#forgotPinOk').onclick=()=>$('#forgotPinDialog').close();
if(matchMedia('(display-mode: standalone)').matches||navigator.standalone)$('#installBtn').classList.add('hidden');
if('serviceWorker'in navigator)navigator.serviceWorker.register('/sw.js');
boot();
