const enc=new TextEncoder();
const json=(data,status=200,headers={})=>new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json;charset=UTF-8',...headers}});
const err=(m,s=400)=>json({error:m},s);
const id=()=>crypto.randomUUID();
const now=()=>new Date().toISOString();
const b64=a=>btoa(String.fromCharCode(...new Uint8Array(a))).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'');
async function sha(s){return b64(await crypto.subtle.digest('SHA-256',enc.encode(s)))}
async function pinHash(pin,salt,pepper){return sha(`${salt}:${pin}:${pepper}`)}
function cookie(token,max=2592000){return `ifc_session=${token}; Path=/; HttpOnly; Secure; SameSite=Strict; Max-Age=${max}`}
function getCookie(req,n){return (req.headers.get('cookie')||'').split(';').map(x=>x.trim()).find(x=>x.startsWith(n+'='))?.slice(n.length+1)||''}
async function auth(req,env){const t=getCookie(req,'ifc_session');if(!t)return null;const h=await sha(t);return await env.DB.prepare(`SELECT u.* FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.token_hash=? AND s.expires_at>?`).bind(h,now()).first()}
async function requireUser(req,env){const u=await auth(req,env);if(!u)throw {status:401,message:'لومړی حساب ته ننوځئ'};return u}
async function requireAdmin(req,env){const u=await requireUser(req,env);if(u.role!=='admin'||u.status!=='approved')throw {status:403,message:'اجازه نشته'};return u}
async function parseForm(req){try{return await req.formData()}catch(_){throw {status:400,message:'معلومات سم نه دي'}}}
function validPhone(p){return /^07\d{8}$/.test(p||'')}
function validPin(p){return /^\d{4}$/.test(p||'')}
async function putPhoto(env,key,file){if(!file||!file.size)throw {status:400,message:'عکس انتخاب کړئ'};if(file.size>5*1024*1024)throw {status:400,message:'عکس ډېر لوی دی'};await env.PHOTOS.put(key,await file.arrayBuffer(),{httpMetadata:{contentType:file.type||'image/jpeg',cacheControl:'public, max-age=604800'}});return key}
async function bootstrap(env){if(!env.ADMIN_PHONE||!env.ADMIN_PIN)return;if(!validPhone(env.ADMIN_PHONE)||!validPin(env.ADMIN_PIN))return;const ex=await env.DB.prepare('SELECT id FROM users WHERE phone=?').bind(env.ADMIN_PHONE).first();if(ex)return;const salt=id(),h=await pinHash(env.ADMIN_PIN,salt,env.PIN_PEPPER||'ifc');await env.DB.prepare(`INSERT INTO users(id,full_name,phone,pin_hash,pin_salt,role,status,created_at) VALUES(?,?,?,?,?,'admin','approved',?)`).bind(id(),env.ADMIN_NAME||'اډمین',env.ADMIN_PHONE,h,salt,now()).run()}
function dayKey(iso){const d=new Date(new Date(iso).getTime()+(270-360)*60000);return `${d.getUTCFullYear()}-${String(d.getUTCMonth()+1).padStart(2,'0')}-${String(d.getUTCDate()).padStart(2,'0')}`}
async function api(req,env,path){
 await bootstrap(env);
 if(path==='/api/register'&&req.method==='POST'){const f=await parseForm(req),name=String(f.get('name')||'').trim(),phone=String(f.get('phone')||''),pin=String(f.get('pin')||''),photo=f.get('photo');if(!name)return err('بشپړ نوم ولیکئ');if(!validPhone(phone))return err('د موبایل شمېره سمه ولیکئ');if(!validPin(pin))return err('څلور عددي PIN ولیکئ');if(await env.DB.prepare('SELECT id FROM users WHERE phone=?').bind(phone).first())return err('دا موبایل شمېره مخکې ثبت شوې ده');const uid=id(),salt=id(),h=await pinHash(pin,salt,env.PIN_PEPPER||'ifc'),key=`identity/${uid}/profile.jpg`;await putPhoto(env,key,photo);await env.DB.prepare(`INSERT INTO users(id,full_name,phone,pin_hash,pin_salt,role,status,selfie_path,created_at) VALUES(?,?,?,?,?,'agent','pending',?,?)`).bind(uid,name,phone,h,salt,key,now()).run();return json({ok:true})}
 if(path==='/api/login'&&req.method==='POST'){const {phone,pin}=await req.json();const u=await env.DB.prepare('SELECT * FROM users WHERE phone=?').bind(phone).first();if(!u||await pinHash(String(pin),u.pin_salt,env.PIN_PEPPER||'ifc')!==u.pin_hash)return err('موبایل شمېره یا PIN ناسم دی',401);if(u.status==='rejected')return err('ستاسې حساب بند شوی دی',403);const token=b64(crypto.getRandomValues(new Uint8Array(32))),th=await sha(token),exp=new Date(Date.now()+30*864e5).toISOString();await env.DB.prepare('INSERT INTO sessions(token_hash,user_id,expires_at) VALUES(?,?,?)').bind(th,u.id,exp).run();return json({ok:true},200,{'set-cookie':cookie(token)})}
 if(path==='/api/logout'&&req.method==='POST'){const t=getCookie(req,'ifc_session');if(t)await env.DB.prepare('DELETE FROM sessions WHERE token_hash=?').bind(await sha(t)).run();return json({ok:true},200,{'set-cookie':cookie('',0)})}
 if(path==='/api/me'){const u=await requireUser(req,env);delete u.pin_hash;delete u.pin_salt;return json({profile:u})}
 if(path.startsWith('/api/photo/')&&req.method==='GET'){await requireUser(req,env);const key=decodeURIComponent(path.slice('/api/photo/'.length));const o=await env.PHOTOS.get(key);if(!o)return new Response('Not found',{status:404});const h=new Headers();o.writeHttpMetadata(h);h.set('etag',o.httpEtag);return new Response(o.body,{headers:h})}
 if(path==='/api/orders'&&req.method==='GET'){const u=await requireUser(req,env);if(u.status!=='approved')return err('حساب لا نه دی تایید شوی',403);const url=new URL(req.url),off=Math.max(0,Number(url.searchParams.get('offset')||0)),lim=Math.min(50,Math.max(1,Number(url.searchParams.get('limit')||20)));let q,rs;if(u.role==='agent'){q=env.DB.prepare(`SELECT o.*,u.full_name creator_name FROM orders o JOIN users u ON u.id=o.created_by WHERE o.created_by=? ORDER BY o.created_at DESC LIMIT ? OFFSET ?`);rs=await q.bind(u.id,lim+1,off).all()}else{q=env.DB.prepare(`SELECT o.*,u.full_name creator_name FROM orders o JOIN users u ON u.id=o.created_by ORDER BY o.created_at DESC LIMIT ? OFFSET ?`);rs=await q.bind(lim+1,off).all()}return json({orders:rs.results.slice(0,lim),hasMore:rs.results.length>lim})}
 if(path==='/api/orders'&&req.method==='POST'){const u=await requireUser(req,env);if(u.role!=='agent'||u.status!=='approved')return err('یوازې شاګرد جنس ثبتولی شي',403);const f=await parseForm(req),oid=String(f.get('id')||''),name=String(f.get('product_name')||'').trim(),cp=String(f.get('customer_phone')||'').trim(),province=String(f.get('province')||''),qty=Math.max(1,Number(f.get('quantity')||1)),address=String(f.get('address')||'').trim(),price=Math.max(0,Number(f.get('price')||0)),photo=f.get('photo');if(!name||!cp||!province||!address)return err('ټول معلومات بشپړ کړئ');if(oid){const old=await env.DB.prepare(`SELECT * FROM orders WHERE id=? AND created_by=? AND status='registered'`).bind(oid,u.id).first();if(!old)return err('د اصلاح اجازه نشته',403);let key=old.photo_path;if(photo&&photo.size){key=`orders/${u.id}/${id()}.jpg`;await putPhoto(env,key,photo);if(old.photo_path)await env.PHOTOS.delete(old.photo_path)}await env.DB.prepare(`UPDATE orders SET product_name=?,customer_phone=?,province=?,quantity=?,address=?,price=?,photo_path=? WHERE id=?`).bind(name,cp,province,qty,address,price,key,oid).run();return json({ok:true})}if(!photo||!photo.size)return err('د جنس عکس واخلئ');const key=`orders/${u.id}/${id()}.jpg`,newid=id();await putPhoto(env,key,photo);await env.DB.prepare(`INSERT INTO orders(id,product_name,customer_phone,province,quantity,address,price,photo_path,status,created_by,created_at) VALUES(?,?,?,?,?,?,?,?,'registered',?,?)`).bind(newid,name,cp,province,qty,address,price,key,u.id,now()).run();return json({ok:true})}
 let m=path.match(/^\/api\/orders\/([^/]+)$/);if(m&&req.method==='DELETE'){const u=await requireUser(req,env);const o=await env.DB.prepare(`SELECT * FROM orders WHERE id=? AND created_by=? AND status='registered'`).bind(m[1],u.id).first();if(!o)return err('لېږل شوی یا تسلیم شوی جنس نه شي ډیلیټ کېدای',403);await env.DB.prepare('DELETE FROM orders WHERE id=?').bind(o.id).run();if(o.photo_path)await env.PHOTOS.delete(o.photo_path);return json({ok:true})}
 m=path.match(/^\/api\/orders\/([^/]+)\/advance$/);if(m&&req.method==='POST'){const u=await requireUser(req,env);if(u.role!=='dispatcher'||u.status!=='approved')return err('اجازه نشته',403);const o=await env.DB.prepare(`SELECT * FROM orders WHERE id=? AND status='registered'`).bind(m[1]).first();if(!o)return err('آرډر د پروسس وړ نه دی');const st=o.province==='کندهار'?'delivered':'sent';await env.DB.prepare('UPDATE orders SET status=?,processed_at=? WHERE id=?').bind(st,now(),o.id).run();return json({status:st})}
 if(path==='/api/stats'){const u=await requireUser(req,env),rs=await env.DB.prepare(`SELECT province,price,status,processed_at,created_by FROM orders WHERE processed_at IS NOT NULL ORDER BY processed_at DESC LIMIT 5000`).all();const key=dayKey(now());let a={otherCount:0,otherMoney:0,kandaharCount:0,kandaharMoney:0};for(const o of rs.results){if(dayKey(o.processed_at)!==key||(u.role==='agent'&&o.created_by!==u.id))continue;if(o.province==='کندهار'&&o.status==='delivered'){a.kandaharCount++;a.kandaharMoney+=Number(o.price)}else if(o.province!=='کندهار'&&o.status==='sent'){a.otherCount++;a.otherMoney+=Number(o.price)}}return json(a)}
 if(path==='/api/users'){await requireAdmin(req,env);const rs=await env.DB.prepare('SELECT id,full_name,phone,role,status,selfie_path,created_at FROM users ORDER BY created_at DESC').all();return json({users:rs.results})}
 m=path.match(/^\/api\/users\/([^/]+)$/);if(m&&req.method==='PATCH'){await requireAdmin(req,env);const {action}=await req.json();if(!['agent','dispatcher','reject'].includes(action))return err('ناسم عمل');await env.DB.prepare('UPDATE users SET role=?,status=? WHERE id=? AND role<>?').bind(action==='reject'?'agent':action,action==='reject'?'rejected':'approved',m[1],'admin').run();return json({ok:true})}
 m=path.match(/^\/api\/users\/([^/]+)\/pin$/);if(m&&req.method==='PATCH'){await requireAdmin(req,env);const {pin}=await req.json();if(!validPin(String(pin)))return err('څلور عددي PIN ولیکئ');const salt=id(),h=await pinHash(String(pin),salt,env.PIN_PEPPER||'ifc');await env.DB.prepare('UPDATE users SET pin_hash=?,pin_salt=? WHERE id=?').bind(h,salt,m[1]).run();await env.DB.prepare('DELETE FROM sessions WHERE user_id=?').bind(m[1]).run();return json({ok:true})}
 if(path==='/api/report'){const u=await requireUser(req,env),rs=await env.DB.prepare(`SELECT province,price,status,processed_at,created_by FROM orders WHERE processed_at IS NOT NULL ORDER BY processed_at DESC LIMIT 5000`).all(),map=new Map();for(const o of rs.results){if(u.role==='agent'&&o.created_by!==u.id)continue;const key=dayKey(o.processed_at);if(!map.has(key))map.set(key,{key,otherCount:0,otherMoney:0,kandaharCount:0,kandaharMoney:0});const d=map.get(key);if(o.province==='کندهار'&&o.status==='delivered'){d.kandaharCount++;d.kandaharMoney+=Number(o.price)}else if(o.province!=='کندهار'&&o.status==='sent'){d.otherCount++;d.otherMoney+=Number(o.price)}}return json({days:[...map.values()].sort((a,b)=>b.key.localeCompare(a.key))})}
 return err('API ونه موندل شو',404)
}
export default {async fetch(req,env){const url=new URL(req.url);try{if(url.pathname.startsWith('/api/'))return await api(req,env,url.pathname);return env.ASSETS.fetch(req)}catch(e){return err(e?.message||'د سرور ستونزه',e?.status||500)}}}
